config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: %i[ new create destroy ]
  resources :users, only: %i[ new create show edit update]
  resources :favorites, only: %i[ index create destroy ]
  # mount LetterOpenerWeb::Engine, at: "/inbox" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :content, presence: true
  validates :image, presence: true
  mount_uploader :image, ImageUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  has_many :favorites, dependent: :destroy
  before_validation { email.downcase! }
  validates :profile_picture, presence: true
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, length: { minimum: 1 }
  mount_uploader :profile_picture, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  before_action :ensure_correct_user, only: %i[ edit update destroy ]
  before_action :require_login

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        # PostMailer.post_mail(@blog).deliver
        redirect_to blogs_path, notice: "投稿しました！"
      else
        render :new
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "編集しました！"
    else
      render :edit
    end
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "削除しました" }
      format.json { head :no_content }
    end
  end

  private
  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:content, :image, :image_cache, :user_id)
  end

  def ensure_correct_user
    blog = Blog.find(params[:id])
    if blog.user_id != current_user.id
      redirect_to blogs_path, notice: "権限がありません"
    end
  end

  def require_login
    redirect_to new_session_path unless logged_in?
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites
  end

  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notece] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i[ new create edit update ]
  before_action :ensure_correct_user, only: %i[ edit update ]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id), notice: "登録が完了しました！"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "プロフィールを更新しました！"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :profile_picture, :image_cashe, :user_id)
  end

  def ensure_correct_user
    user = User.find(params[:id])
    if user.id != current_user.id
      redirect_to blogs_path, notice: "権限がありません"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == "new" || action_name == "create"
      confirm_blogs_path
    elsif action_name == "edit"
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true, url: choose_new_or_edit ) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= blog.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <% if @blog.image && @blog.image.url %>
      <%= image_tag @blog.image.url, class: "img" %>
    <% end %>
    <%= form.label :image %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to "Homeへ戻る", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で送信する</h3>
<%= form_with(model: @blog, local: true) do |form| %>
  <% if @blog.image && @blog.image.url %>
    <%= image_tag @blog.image.url, class: "img" %>
  <% end %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <p>本文：<%= @blog.content %></p>
  <%= form.submit "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/blogs/edit.html.erb
<h1>Edit</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Home</h1>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Image</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= link_to blog.user.name, user_path(blog.user) %></td>
        <td><%= image_tag blog.image.url, class:'index_image' %></td>
        <td><%= blog.content.truncate(20) %></td>
        <td><%= link_to '詳細を見る', blog_path(blog.id) %></td>
        <% if blog.user.id==@current_user.id %>
        <td><%= link_to '編集する', edit_blog_path(blog) %></td>
        <td><%= link_to '削除する', blog, method: :delete, data: { confirm: '削除してもよろしいですか？' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to '新しく投稿する', new_blog_path %>
<%= link_to 'お気に入り', favorites_path %>

app/views/blogs/new.html.erb
<%= render 'form', blog: @blog %>

app/views/blogs/show.html.erb
<p>
  <strong>User:</strong>
  <%= @blog.user.name %>
</p>
<p>
  <strong>Image:</strong>
  <%= image_tag @blog.image.url, class: "img" %>
</p>
<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>
<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<% if @blog.user_id == current_user.id %>
  <%= link_to 'Edit', edit_blog_path(@blog) %>
<% end %>
<%= link_to 'Back', blogs_path %>

app/views/favorites/index.html.erb
<h1>お気に入り</h1>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Image</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @favorites.each do |favorite| %>
      <tr>
        <td><%= link_to favorite.user.name, user_path(favorite.user) %></td>
        <td><%= image_tag favorite.blog.image.url, class:'index_image' %></td>
        <td><%= favorite.blog.content.truncate(20) %></td>
        <td><%= link_to '詳細を見る', blog_path(favorite.blog) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsKadai3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <header class="header">
        <% if logged_in? %>
          <%= link_to "Home", blogs_path %>
          <%= link_to "Profile", user_path(current_user.id) %>
          <%= link_to "Logout", session_path(current_user.id), method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_path %>
          <%= link_to "Login", new_session_path %>
        <% end %>
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        <% end %>
      </header>
      <%= yield %>
      <footer>
        <p>運営会社DIVE INTO CODE株式会社</p>
        <p>© 2015-2016 DIVE INTO CODE Corp.</p>
      </footer>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :profile_picture %>
  <% if @user.profile_picture && @user.profile_picture.url %>
    <%= image_tag @user.profile_picture.url, class: "img" %>
  <% end %>
  <%= f.file_field :profile_picture %>
  <%= f.hidden_field :profile_picture_cashe %>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/edit.html.erb
<h2>プロフィール編集</h2>
<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :profile_picture %>
  <%= image_tag(@user.profile_picture.url) if @user.profile_picture && @user.profile_picture.url %>
  <%= f.file_field :profile_picture %>
  <%= f.hidden_field :profile_picture_cashe %>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<div class="field">
  <%= image_tag @user.profile_picture.url, class: "profile_img" %>
</div>
<p>メールアドレス: <%= @user.email %></p>
<% if @user.id==@current_user.id %>
  <%= link_to '編集する', edit_user_path(@user.id) %>
<% end %>
<%= link_to '戻る', blogs_path %>